// <auto-generated />
using System;
using Conduit.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Conduit.Data.Migrations
{
    [DbContext(typeof(ConduitContext))]
    [Migration("20210316034755_DbContextAll")]
    partial class DbContextAll
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Conduit.Data.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varbinary(128)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varbinary(128)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Email" }, "IX_Accounts_Email_Unique")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Conduit.Data.Commentary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<int>("EditorialId")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getutcdate())");

                    b.HasKey("Id");

                    b.HasIndex("EditorialId");

                    b.HasIndex("PersonId");

                    b.ToTable("Commentaries");
                });

            modelBuilder.Entity("Conduit.Data.Editorial", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getutcdate())");

                    b.HasKey("ID");

                    b.HasIndex("PersonId");

                    b.ToTable("Editorials");
                });

            modelBuilder.Entity("Conduit.Data.Favorite", b =>
                {
                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<int>("EditorialId")
                        .HasColumnType("int");

                    b.HasKey("PersonId", "EditorialId");

                    b.HasIndex("EditorialId");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("Conduit.Data.Follow", b =>
                {
                    b.Property<int>("Follower")
                        .HasColumnType("int");

                    b.Property<int>("Following")
                        .HasColumnType("int");

                    b.HasKey("Follower", "Following");

                    b.HasIndex("Following");

                    b.ToTable("Follows");
                });

            modelBuilder.Entity("Conduit.Data.Person", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Bio")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasDefaultValue("'https://static.productionready.io/images/smiley-cyrus.jpg'");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("People");
                });

            modelBuilder.Entity("Conduit.Data.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("EditorialTag", b =>
                {
                    b.Property<int>("EditorialsID")
                        .HasColumnType("int");

                    b.Property<int>("TagsId")
                        .HasColumnType("int");

                    b.HasKey("EditorialsID", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("EditorialTag");
                });

            modelBuilder.Entity("Conduit.Data.Commentary", b =>
                {
                    b.HasOne("Conduit.Data.Editorial", "Editorial")
                        .WithMany("Commentaries")
                        .HasForeignKey("EditorialId")
                        .HasConstraintName("FK_Commentary_Editorials")
                        .IsRequired();

                    b.HasOne("Conduit.Data.Person", "Person")
                        .WithMany("Commentaries")
                        .HasForeignKey("PersonId")
                        .HasConstraintName("FK_Commentaries_People")
                        .IsRequired();

                    b.Navigation("Editorial");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Conduit.Data.Editorial", b =>
                {
                    b.HasOne("Conduit.Data.Person", "Person")
                        .WithMany("Editorials")
                        .HasForeignKey("PersonId")
                        .HasConstraintName("FK_Articles_People")
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Conduit.Data.Favorite", b =>
                {
                    b.HasOne("Conduit.Data.Editorial", "Editorial")
                        .WithMany("Favorites")
                        .HasForeignKey("EditorialId")
                        .HasConstraintName("FK_Favorites_Editorials")
                        .IsRequired();

                    b.HasOne("Conduit.Data.Person", "Person")
                        .WithMany("Favorites")
                        .HasForeignKey("PersonId")
                        .HasConstraintName("FK_Favorites_People")
                        .IsRequired();

                    b.Navigation("Editorial");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Conduit.Data.Follow", b =>
                {
                    b.HasOne("Conduit.Data.Person", "FollowerNavigation")
                        .WithMany("FollowerNavigations")
                        .HasForeignKey("Follower")
                        .HasConstraintName("FK_Follower_Profiles")
                        .IsRequired();

                    b.HasOne("Conduit.Data.Person", "FollowingNavigation")
                        .WithMany("FollowingNavigations")
                        .HasForeignKey("Following")
                        .HasConstraintName("FK_Following_Profiles")
                        .IsRequired();

                    b.Navigation("FollowerNavigation");

                    b.Navigation("FollowingNavigation");
                });

            modelBuilder.Entity("Conduit.Data.Person", b =>
                {
                    b.HasOne("Conduit.Data.Account", "Account")
                        .WithOne("Person")
                        .HasForeignKey("Conduit.Data.Person", "Id")
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("EditorialTag", b =>
                {
                    b.HasOne("Conduit.Data.Editorial", null)
                        .WithMany()
                        .HasForeignKey("EditorialsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Conduit.Data.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Conduit.Data.Account", b =>
                {
                    b.Navigation("Person");
                });

            modelBuilder.Entity("Conduit.Data.Editorial", b =>
                {
                    b.Navigation("Commentaries");

                    b.Navigation("Favorites");
                });

            modelBuilder.Entity("Conduit.Data.Person", b =>
                {
                    b.Navigation("Commentaries");

                    b.Navigation("Editorials");

                    b.Navigation("Favorites");

                    b.Navigation("FollowerNavigations");

                    b.Navigation("FollowingNavigations");
                });
#pragma warning restore 612, 618
        }
    }
}
